import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./projectflow.css";
const API = "";

function errorText(response, data) {
  const detail = data?.detail ?? data?.message ?? response.statusText;
  const readable = typeof detail === "string" ? detail : JSON.stringify(detail, null, 2);
  return `HTTP ${response.status}\n${readable}${import.meta.env.DEV && data?.traceback ? `\n\n${data.traceback}` : ""}`;
}
async function api(path, options = {}) {
  const headers = { ...(options.body ? { "Content-Type": "application/json" } : {}), ...(localStorage.getItem("projectflow_token") ? { Authorization: `Bearer ${localStorage.getItem("projectflow_token")}` } : {}), ...options.headers };
  const response = await fetch(API + path, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(errorText(response, data));
  return data;
}
const initials = (name = "?") => name.split(/\s+/).map(part => part[0]).join("").slice(0, 2).toUpperCase();
const dateLabel = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "No due date";

function Notice({ error, success }) {
  if (!error && !success) return null;
  return <div className={`notice ${error ? "error" : "success"}`}>{error || success}</div>;
}

function AuthScreen({ onLogin }) {
  const [signup, setSignup] = useState(false), [form, setForm] = useState({ name: "", email: "", password: "" }), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function submit(event) {
    event.preventDefault(); setError(""); setBusy(true);
    try { const data = await api(`/auth/${signup ? "register" : "login"}`, { method: "POST", body: JSON.stringify(form) }); localStorage.setItem("projectflow_token", data.token); onLogin(data.user); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  return <main className="auth-page"><section className="auth-art"><div className="brand">project<i>flow</i></div><h1>Make good work<br/>flow together.</h1><p>A calm space to plan projects, keep the team in sync, and turn big ideas into clear next steps.</p></section><section className="auth-card-wrap"><div className="auth-card"><h2>{signup ? "Create your account" : "Welcome back"}</h2><p>{signup ? "Start organizing your next project." : "Sign in to pick up where you left off."}</p><Notice error={error}/><form onSubmit={submit}>{signup && <label>Your name<input className="input" required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label>}<label>Email address<input className="input" type="email" required value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></label><label>Password<input className="input" type="password" required minLength="8" value={form.password} onChange={e => setForm({...form,password:e.target.value})}/></label><button className="btn" disabled={busy}>{busy ? "Please wait…" : signup ? "Create account" : "Sign in"}</button></form><div className="auth-switch">{signup ? "Already have an account?" : "New to ProjectFlow?"} <button className="btn ghost small" onClick={() => {setSignup(!signup);setError("")}}>{signup ? "Sign in" : "Create an account"}</button></div></div></section></main>;
}

function MemberAvatars({ members = [] }) { return <div className="member-stack">{members.slice(0, 4).map(m => <span key={m.id} className="avatar" title={m.name}>{initials(m.name)}</span>)}{members.length > 4 && <span className="avatar">+{members.length - 4}</span>}</div>; }

function App() {
  const [user, setUser] = useState(null), [loading, setLoading] = useState(true), [projects, setProjects] = useState([]), [myTasks, setMyTasks] = useState([]), [selectedId, setSelectedId] = useState(Number(new URLSearchParams(location.search).get("project")) || null), [project, setProject] = useState(null), [error, setError] = useState(""), [success, setSuccess] = useState(""), [query, setQuery] = useState(""), [menuOpen, setMenuOpen] = useState(false), [modal, setModal] = useState("");
  const [newProject, setNewProject] = useState({ name: "", description: "", due_date: "" }), [memberEmail, setMemberEmail] = useState(""), [taskForm, setTaskForm] = useState({ title: "", description: "", priority: "medium", due_date: "", assigned_to: "" }), [taskFilter, setTaskFilter] = useState(""), [filterStatus, setFilterStatus] = useState(""), [filterPriority, setFilterPriority] = useState("");
  const [breakdownText, setBreakdownText] = useState(""), [suggestions, setSuggestions] = useState([]), [breakdownTarget, setBreakdownTarget] = useState(""), [assistantQuestion, setAssistantQuestion] = useState(""), [assistantAnswer, setAssistantAnswer] = useState(""), [assistantBusy, setAssistantBusy] = useState(false), [breakdownBusy, setBreakdownBusy] = useState(false);
  const [editingTask, setEditingTask] = useState(null), [editingProject, setEditingProject] = useState(false), [dragging, setDragging] = useState(null);
  const [theme, setTheme] = useState(localStorage.getItem("theme") || "light");
  useEffect(() => { document.documentElement.setAttribute("data-theme", theme); localStorage.setItem("theme", theme); }, [theme]);
  async function loadProjects(search = query) { const result = await api(`/projects${search ? `?q=${encodeURIComponent(search)}` : ""}`); setProjects(result.projects); }
  async function loadProject(id = selectedId) { if (!id) return; const result = await api(`/projects/${id}`); setProject(result); }
  async function loadMyTasks() { const result = await api("/tasks/mine"); setMyTasks(result.tasks); }
  useEffect(() => { if (!localStorage.getItem("projectflow_token")) { setLoading(false); return; } api("/auth/me").then(async me => { setUser(me); await loadProjects(""); }).catch(() => localStorage.removeItem("projectflow_token")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (user) loadMyTasks().catch(e => setError(e.message)); }, [user]);
  useEffect(() => { const onHistoryChange = () => { setSelectedId(Number(new URLSearchParams(location.search).get("project")) || null); setProject(null); }; addEventListener("popstate", onHistoryChange); return () => removeEventListener("popstate", onHistoryChange); }, []);
  useEffect(() => { if (user && selectedId) loadProject(selectedId).catch(e => setError(e.message)); }, [user, selectedId]);
  useEffect(() => { const timer = setTimeout(() => { if (user && !selectedId) loadProjects(query).catch(e => setError(e.message)); }, 250); return () => clearTimeout(timer); }, [query, user, selectedId]);
  async function act(fn, successMessage = "") { setError(""); setSuccess(""); try { await fn(); if (successMessage) setSuccess(successMessage); } catch (e) { setError(e.message); } }
  function openProject(id) { setSelectedId(id); setProject(null); setError(""); setSuccess(""); history.pushState({}, "", `/?project=${id}`); setMenuOpen(false); }
  function dashboard() { setSelectedId(null); setProject(null); history.pushState({}, "", "/"); setMenuOpen(false); }
  async function signOut() { await act(async () => { try { await api("/auth/logout", { method: "POST" }); } finally { localStorage.removeItem("projectflow_token"); setUser(null); setProject(null); setSelectedId(null); } }); }
  async function createProject(event) { event.preventDefault(); await act(async () => { const created = await api("/projects", { method: "POST", body: JSON.stringify({ ...newProject, due_date: newProject.due_date || null }) }); setNewProject({ name: "", description: "", due_date: "" }); setModal(""); await loadProjects(""); openProject(created.id); }, "Project created."); }
  async function saveProject(event) { event.preventDefault(); await act(async () => { await api(`/projects/${project.id}`, { method: "PUT", body: JSON.stringify({ name: project.name, description: project.description, status: project.status, due_date: project.due_date || null }) }); setEditingProject(false); await loadProject(); await loadProjects(""); }, "Project updated."); }
  async function deleteProject() { if (!confirm("Delete this project and all its tasks?")) return; await act(async () => { await api(`/projects/${project.id}`, { method: "DELETE" }); dashboard(); await loadProjects(""); }, "Project deleted."); }
  async function addMember(event) { event.preventDefault(); await act(async () => { await api(`/projects/${project.id}/members`, { method: "POST", body: JSON.stringify({ email: memberEmail }) }); setMemberEmail(""); await loadProject(); }, "Team member added."); }
  async function removeMember(id) { await act(async () => { await api(`/projects/${project.id}/members/${id}`, { method: "DELETE" }); await loadProject(); }, "Member removed."); }
  async function saveTask(event) { event.preventDefault(); const form = editingTask || taskForm; await act(async () => { await api(editingTask ? `/tasks/${editingTask.id}` : `/projects/${project.id}/tasks`, { method: editingTask ? "PUT" : "POST", body: JSON.stringify({ ...form, assigned_to: form.assigned_to ? Number(form.assigned_to) : null, due_date: form.due_date || null }) }); setTaskForm({ title: "", description: "", priority: "medium", due_date: "", assigned_to: "" }); setEditingTask(null); setModal(""); await loadProject(); await loadProjects(""); await loadMyTasks(); }, editingTask ? "Task updated." : "Task created."); }
  async function moveTask(task, status) { await act(async () => { await api(`/tasks/${task.id}`, { method: "PUT", body: JSON.stringify({ title: task.title, description: task.description || "", priority: task.priority, status, due_date: task.due_date || null, assigned_to: task.assigned_to }) }); await loadProject(); await loadProjects(""); await loadMyTasks(); }); }
  async function deleteTask(task) { if (!confirm("Delete this task?")) return; await act(async () => { await api(`/tasks/${task.id}`, { method: "DELETE" }); await loadProject(); await loadProjects(""); }, "Task deleted."); }
  async function comment(task) { const content = prompt("Add a comment"); if (!content?.trim()) return; await act(async () => { await api(`/tasks/${task.id}/comments`, { method: "POST", body: JSON.stringify({ content }) }); await loadProject(); }, "Comment added."); }
  async function generateBreakdown(event) { event.preventDefault(); setBreakdownBusy(true); try { await act(async () => { const result = await api("/ai/task-breakdown", { method: "POST", body: JSON.stringify({ requirement: breakdownText }) }); setSuggestions(result.suggestions.map((title, index) => ({ title, checked: true, key: index }))); }, "Suggestions are ready to review."); } finally { setBreakdownBusy(false); } }
  async function addSuggested() { const picked = suggestions.filter(s => s.checked); const targetId = selectedId || Number(breakdownTarget); if (!picked.length || !targetId) return; await act(async () => { for (const s of picked) await api(`/projects/${targetId}/tasks`, { method: "POST", body: JSON.stringify({ title: s.title, description: "", status: "todo", priority: "medium", assigned_to: null }) }); setSuggestions([]); setBreakdownText(""); setModal(""); if (selectedId === targetId) await loadProject(); await loadProjects(""); }, `${picked.length} reviewed task${picked.length === 1 ? "" : "s"} added.`); }
  async function askAssistant(event) { event.preventDefault(); setAssistantAnswer(""); setAssistantBusy(true); try { await act(async () => { const result = await api("/ai/project-assistant", { method: "POST", body: JSON.stringify({ question: assistantQuestion, project_id: project?.id || null }) }); setAssistantAnswer(result.answer); }); } finally { setAssistantBusy(false); } }
  if (loading) return <div className="empty">Loading ProjectFlow…</div>;
  if (!user) return <AuthScreen onLogin={async who => { setUser(who); await loadProjects(""); }} />;
  const totalTasks = projects.reduce((sum, p) => sum + p.total_tasks, 0), completed = projects.reduce((sum, p) => sum + p.done_tasks, 0), overdue = project?.tasks?.filter(t => t.due_date && t.due_date < new Date().toISOString().slice(0, 10) && t.status !== "done").length || 0;
  const taskStatuses = [{ key: "todo", label: "To do" }, { key: "in_progress", label: "In progress" }, { key: "done", label: "Completed" }];
  const tasks = (project?.tasks || []).filter(t => (!taskFilter || `${t.title} ${t.description || ""}`.toLowerCase().includes(taskFilter.toLowerCase())) && (!filterStatus || t.status === filterStatus) && (!filterPriority || t.priority === filterPriority));
  const taskFormValue = editingTask || taskForm; const updateTaskField = (key, value) => editingTask ? setEditingTask({ ...editingTask, [key]: value }) : setTaskForm({ ...taskForm, [key]: value });
  return <div className="shell"><aside className={`sidebar ${menuOpen ? "mobile-open" : ""}`}><div className="brand">project<i>flow</i></div><div><div className="workspace-label">Workspace</div><button className={`side-link ${!selectedId ? "active" : ""}`} style={{width:"100%",textAlign:"left",border:0,background:!selectedId?"#294439":"transparent"}} onClick={dashboard}>◫ &nbsp; Overview</button></div><div><div className="workspace-label">Your projects</div><nav>{projects.map(p => <button key={p.id} className={`side-link side-project ${selectedId === p.id ? "active" : ""}`} style={{width:"100%",textAlign:"left",border:0,background:selectedId===p.id?"#294439":"transparent"}} onClick={() => openProject(p.id)}><i className="dot"/> {p.name}</button>)}</nav><button className="side-link side-action" onClick={() => setModal("project")}>＋ &nbsp; New project</button></div><div className="sidebar-bottom"><div className="user-chip"><span className="avatar">{initials(user.name)}</span><span className="user-copy">{user.name}<small>{user.email}</small></span></div></div></aside>
  <main className="main"><header className="topbar"><div><button className="mobile-menu iconbtn" onClick={() => setMenuOpen(!menuOpen)}>☰</button><span className="crumb">Workspace&nbsp; / &nbsp;{project?.name || "Overview"}</span></div><div className="top-actions"><button className="btn ghost small" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{theme === "dark" ? "☼ Light" : "◐ Dark"}</button><button className="btn light small" onClick={signOut}>↪ Sign out</button><span className="avatar">{initials(user.name)}</span></div></header><div className="content"><Notice error={error} success={success}/>
  {!selectedId ? <><div className="heading-row"><div><div className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</div><h1>Good work starts here, {user.name.split(" ")[0]}.</h1><p className="subtitle">A clear view of what’s moving across your workspace.</p></div></div>
  <div className="grid-stats"><div className="stat"><label>Total projects</label><strong>{projects.length}</strong><div className="hint">Across your workspace</div></div><div className="stat"><label>Active projects</label><strong>{projects.filter(p => p.status !== "completed").length}</strong><div className="hint">In progress right now</div></div><div className="stat"><label>Completed projects</label><strong>{projects.filter(p => p.status === "completed").length}</strong><div className="hint">Finished work</div></div><div className="stat"><label>Total tasks</label><strong>{totalTasks}</strong><div className="hint">Across every project</div></div><div className="stat"><label>Completed tasks</label><strong>{completed}</strong><div className="hint">Done across projects</div></div><div className="stat"><label>Pending tasks</label><strong>{totalTasks - completed}</strong><div className="hint">Ready for the next step</div></div><div className="stat"><label>Overdue tasks</label><strong>{projects.reduce((sum,p)=>sum+(p.overdue_tasks||0),0)}</strong><div className="hint">Past due and still open</div></div></div>
  <div className="heading-row"><div><h2 style={{font:"700 19px Manrope",margin:0}}>Your projects</h2><p className="subtitle">Keep the important work in motion.</p></div><input className="input search" placeholder="Search projects…" value={query} onChange={e => setQuery(e.target.value)}/></div>
  <div className="project-grid">{projects.map(p => <article className="project-card" key={p.id}><a href={`/?project=${p.id}`} className="project-title" onClick={e => {e.preventDefault();openProject(p.id)}}>{p.name}</a><p>{p.description || "Add a short project description to help everyone stay aligned."}</p><div className="progress-track"><div className="progress-fill" style={{width:`${p.progress}%`}}/></div><div className="project-meta"><span>{p.done_tasks} of {p.total_tasks} tasks done</span><span>{p.progress}%</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:15}}><MemberAvatars members={p.members}/><span style={{fontSize:11,color:"#7f8a81"}}>{p.due_date ? `Due ${dateLabel(p.due_date)}` : "No deadline"}</span></div></article>)}{!projects.length && <div className="panel empty">No projects match yet. Start with a new project.</div>}</div>
  <div className="two-panels"><section className="panel"><h2>Assigned to me <span className="count">{myTasks.length}</span></h2>{myTasks.slice(0,8).map(task=><button key={task.id} className="member-row" style={{width:"100%",border:0,background:"transparent",textAlign:"left",cursor:"pointer"}} onClick={()=>openProject(task.project_id)}><span><strong style={{fontSize:13}}>{task.title}</strong><small style={{display:"block",color:"#849087",marginTop:4}}>{task.project_name} · {task.status.replace("_"," ")} · {task.due_date ? `Due ${dateLabel(task.due_date)}` : "No deadline"}</small></span><span className={`tag ${task.priority}`}>{task.priority}</span></button>)}{!myTasks.length&&<p className="subtitle">Tasks assigned to you will show up here.</p>}</section><section className="panel"><h2>✦ &nbsp;Task breakdown</h2><p className="subtitle">Turn a big requirement into practical next steps.</p><textarea className="textarea" rows="3" placeholder="For example: Build an e-commerce website…" value={breakdownText} onChange={e => setBreakdownText(e.target.value)}/><button className="btn" style={{marginTop:10}} onClick={()=>{setBreakdownTarget("");setModal("ai")}}>Review task suggestions</button></section></div><div className="panel" style={{marginTop:15}}><h2>✧ &nbsp;Project assistant</h2><p className="subtitle">Ask for planning advice across your workspace.</p><form className="form-row" onSubmit={askAssistant}><input className="input" placeholder="What should I focus on today?" value={assistantQuestion} onChange={e => setAssistantQuestion(e.target.value)} required/><button className="btn" disabled={assistantBusy}>{assistantBusy ? "Thinking…" : "Ask"}</button></form>{assistantAnswer && <div className="ai-result">{assistantAnswer}</div>}</div></> : !project ? <div className="empty">Loading project…</div> : <>
  <div className="heading-row"><div><div className="eyebrow">Project space</div>{editingProject ? <form className="form-stack" onSubmit={saveProject}><input className="input" value={project.name} onChange={e => setProject({...project,name:e.target.value})}/><textarea className="textarea" value={project.description || ""} onChange={e => setProject({...project,description:e.target.value})}/><div className="form-row"><input className="input" type="date" value={project.due_date || ""} onChange={e => setProject({...project,due_date:e.target.value})}/><select className="select" value={project.status} onChange={e => setProject({...project,status:e.target.value})}><option value="active">Active</option><option value="completed">Completed</option></select><button className="btn">Save</button></div></form> : <><h1>{project.name}</h1><p className="subtitle">{project.description || "A shared space for plans, tasks, and good work."}</p></>}</div><div className="task-actions"><button className="btn light" onClick={() => setModal("task")}>＋ Add task</button>{project.is_owner && <><button className="btn ghost" onClick={() => setEditingProject(!editingProject)}>{editingProject?"Cancel":"Edit"}</button><button className="btn danger" onClick={deleteProject}>Delete</button></>}</div></div>
  <div className="grid-stats"><div className="stat"><label>Progress</label><strong>{project.progress}%</strong><div className="progress-track"><div className="progress-fill" style={{width:`${project.progress}%`}}/></div></div><div className="stat"><label>Total tasks</label><strong>{project.tasks.length}</strong><div className="hint">{project.tasks.filter(t=>t.status==="done").length} completed</div></div><div className="stat"><label>Pending tasks</label><strong>{project.tasks.filter(t=>t.status!=="done").length}</strong><div className="hint">Still to be completed</div></div><div className="stat"><label>Overdue</label><strong>{overdue}</strong><div className="hint">Past due and still open</div></div></div>
  <div className="toolbar"><input className="input search" placeholder="Search tasks…" value={taskFilter} onChange={e=>setTaskFilter(e.target.value)}/><select className="select" style={{maxWidth:170}} value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">All statuses</option><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Completed</option></select><select className="select" style={{maxWidth:150}} value={filterPriority} onChange={e=>setFilterPriority(e.target.value)}><option value="">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><button className="btn light" onClick={()=>setModal("ai")}>✦ Break down a requirement</button><button className="btn light" onClick={()=>setModal("assistant")}>✧ Ask project assistant</button></div>
  <section className="board">{taskStatuses.map(column => {const items=tasks.filter(t=>t.status===column.key);return <div className="column" key={column.key}><div className="column-head">{column.label}<span className="count">{items.length}</span></div><div className="task-list" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const task=dragging;setDragging(null);if(task&&task.status!==column.key)moveTask(task,column.key)}}>{items.map(task=><article key={task.id} className="task-card" draggable onDragStart={()=>setDragging(task)}><div className="task-title">{task.title}</div>{task.description&&<p className="task-desc">{task.description}</p>}<div className="task-footer"><span className={`tag ${task.priority}`}>{task.priority}</span><span className="task-date">{dateLabel(task.due_date)}</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:10}}><span className="task-assignee">{task.assignee_name ? <><span className="avatar" style={{width:23,height:23,fontSize:9}}>{initials(task.assignee_name)}</span>{task.assignee_name}</> : "Unassigned"}</span><span className="task-actions"><button title="Comment" className="iconbtn" onClick={()=>comment(task)}>◌</button><button title="Edit" className="iconbtn" onClick={()=>{setEditingTask({...task,due_date:task.due_date||"",assigned_to:task.assigned_to||""});setModal("task")}}>✎</button><button title="Delete" className="iconbtn" onClick={()=>deleteTask(task)}>×</button></span></div>{task.comments?.length>0&&<div className="comment-line">{task.comments.length} comment{task.comments.length===1?"":"s"} · {task.comments.at(-1).author_name}: {task.comments.at(-1).content}</div>}</article>)}</div></div>})}</section>
  <div className="two-panels"><section className="panel"><h2>Project team <span className="count">{project.members.length}</span></h2>{project.members.map(m=><div className="member-row" key={m.id}><div className="member-identity"><span className="avatar">{initials(m.name)}</span><span>{m.name}<small>{m.email}</small></span></div>{project.is_owner&&m.id!==project.owner_id&&<button className="btn danger small" onClick={()=>removeMember(m.id)}>Remove</button>}</div>)}{project.is_owner&&<form className="form-row" style={{marginTop:14}} onSubmit={addMember}><input className="input" type="email" placeholder="Add registered member by email" required value={memberEmail} onChange={e=>setMemberEmail(e.target.value)}/><button className="btn">Add</button></form>}</section><section className="panel"><h2>Project assistant</h2><p className="subtitle">Advice grounded in this project’s current tasks.</p><form className="form-row" onSubmit={askAssistant}><input className="input" placeholder="What should I work on next?" required value={assistantQuestion} onChange={e=>setAssistantQuestion(e.target.value)}/><button className="btn" disabled={assistantBusy}>{assistantBusy ? "Thinking…" : "Ask"}</button></form>{assistantAnswer&&<div className="ai-result">{assistantAnswer}</div>}</section></div>
  </>}
  </div></main>
  {modal && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setModal("");setEditingTask(null)}}}><div className="modal"><div className="modal-head"><h2>{modal==="project"?"Create a project":modal==="task"?(editingTask?"Edit task":"Add a task"):modal==="ai"?"Task breakdown":"Project assistant"}</h2><button className="iconbtn" onClick={()=>{setModal("");setEditingTask(null)}}>×</button></div><Notice error={error} success={success}/>
  {modal==="project"&&<form className="form-stack" onSubmit={createProject}><label className="field-label">Project name<input className="input" required value={newProject.name} onChange={e=>setNewProject({...newProject,name:e.target.value})}/></label><label className="field-label">Description<textarea className="textarea" rows="3" value={newProject.description} onChange={e=>setNewProject({...newProject,description:e.target.value})}/></label><label className="field-label">Due date<input className="input" type="date" value={newProject.due_date} onChange={e=>setNewProject({...newProject,due_date:e.target.value})}/></label><button className="btn">Create project</button></form>}
  {modal==="task"&&<form className="form-stack" onSubmit={saveTask}><label className="field-label">Task title<input className="input" required value={taskFormValue.title} onChange={e=>updateTaskField("title",e.target.value)}/></label><label className="field-label">Description<textarea className="textarea" rows="3" value={taskFormValue.description||""} onChange={e=>updateTaskField("description",e.target.value)}/></label><div className="form-row"><label className="field-label" style={{flex:1}}>Priority<select className="select" value={taskFormValue.priority} onChange={e=>updateTaskField("priority",e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label className="field-label" style={{flex:1}}>Status<select className="select" value={taskFormValue.status||"todo"} onChange={e=>updateTaskField("status",e.target.value)}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></label></div><div className="form-row"><label className="field-label" style={{flex:1}}>Due date<input className="input" type="date" value={taskFormValue.due_date||""} onChange={e=>updateTaskField("due_date",e.target.value)}/></label><label className="field-label" style={{flex:1}}>Assign to<select className="select" value={taskFormValue.assigned_to||""} onChange={e=>updateTaskField("assigned_to",e.target.value)}><option value="">Unassigned</option>{project.members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.email}</option>)}</select></label></div><button className="btn">{editingTask?"Save task":"Create task"}</button></form>}
  {modal==="ai"&&<><p className="subtitle">Review the suggestions and choose which tasks to add. Nothing is saved until you confirm.</p><form className="form-stack" onSubmit={generateBreakdown}><textarea className="textarea" rows="4" placeholder="Describe a big requirement…" value={breakdownText} onChange={e=>setBreakdownText(e.target.value)} required/><button className="btn" disabled={breakdownBusy}>{breakdownBusy ? "Thinking…" : "Generate suggestions"}</button></form>{suggestions.length>0&&<><div style={{marginTop:12}}>{suggestions.map(s=><label className="check-row" key={s.key}><input type="checkbox" checked={s.checked} onChange={()=>setSuggestions(suggestions.map(x=>x.key===s.key?{...x,checked:!x.checked}:x))}/>{s.title}</label>)}</div>{!selectedId&&<label className="field-label" style={{display:"block",marginTop:12}}>Add suggestions to<select className="select" value={breakdownTarget} onChange={e=>setBreakdownTarget(e.target.value)}><option value="">Choose a project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<button className="btn" style={{marginTop:10}} disabled={!selectedId&&!breakdownTarget} onClick={addSuggested}>Add selected tasks</button></>}</>}
  {modal==="assistant"&&<><p className="subtitle">The assistant receives this project’s actual task data.</p><form className="form-row" onSubmit={askAssistant}><input className="input" placeholder="Ask a project question…" value={assistantQuestion} onChange={e=>setAssistantQuestion(e.target.value)} required/><button className="btn" disabled={assistantBusy}>{assistantBusy ? "Thinking…" : "Ask"}</button></form>{assistantAnswer&&<div className="ai-result">{assistantAnswer}</div>}</>}
  </div></div>}
  </div>;
}

const root = createRoot(document.getElementById("react-root"));
root.render(<App/>);
